### ISSUE TITLE
tfoc_SCD can't accept single precision matrix as input?

### ISSUE THREAD

**Issue by iverson333** [cvxr/TFOCS#13]
Hi there, I found the code below works well if input matrix is in double-precision, however it will give the following error if I convert input matrix  into single-precision (btw I'm using MATLAB 2018b)

```
Error using linop_dot (line 16)
First input must be a matrix or cell array of matrices.

Error in tfocs_initialize (line 317)
            affineF{end,k} = linop_dot( affineF{end,k}, adjoint );

Error in tfocs_AT (line 17)
tfocs_initialize

Error in tfocs (line 109)
[ varargout{1:max(nargout,1)} ] = feval( [ 'tfocs_', alg ], smoothF, affineF, projectorF, x0, opts );

Error in tfocs_SCD (line 121)
        [ z, odata, opts ] = tfocs( smoothF, affineF, dualproxF, z0, opts );

Error in TFOCS_exp (line 42)
[x, out, optsOut] = tfocs_SCD( obj, affine, dualProx, mu, x0, z0, opts);
```

Because my actual input would be very large so I have to use single-precision to save memory. Is there any workaround? Thanks!

```
input= [1, 2, 3; 4, 5, 6];
X = input;
% X = single(input);

nFrames  = size(X, 1);
lambda  = 0.05;

opts = [];
opts.stopCrit       = 4;
opts.printEvery     = 10;
opts.tol            = 1e-5;
opts.maxIts         = 100;
opts.errFcn{1}      = @(f,d,p) norm(p{1}+p{2}-X,'fro') / norm(X,'fro');

largescale          = false;

x0      = {X, zeros(size(X))};
z0      = [];

obj    = { prox_nuclear(1,largescale), prox_l1(lambda) };
affine = { 1, 1, -X };
mu = 1e-4;
epsilon  = 0.001;
dualProx = prox_l1(epsilon);

[x, out, optsOut] = tfocs_SCD( obj, affine, dualProx, mu, x0, z0, opts);
```

**Comment by stephenbeckr** [comment]
There's no fundamental reason it can't handle single precision. I went through and fixed the code in a few places (and pushed to the git repo) so your example now works, but there's a chance that another section of code might break in another example -- if that happens, just let us know. 

I think most internal/intermediate variables will automatically be in single precision, but I can't guarantee this (it seems the final output is in single precision, as desired).

**Comment by iverson333** [comment]
Cool! Thanks!
