### ISSUE TITLE
self-defined L1/L2 norm

### ISSUE THREAD

**Issue by snapfinger** [cvxr/TFOCS#14]
Hi there, I posted this question to [cvx forum](http://ask.cvxr.com/t/self-defined-l1-l2-norm-in-tfocs/6326) but there's no response (and I noticed questions about TFOCS posted there rarely got answered) so I'm posting here. Hope it won't cause problem.

I'm modifying the `prox_l1l2.m`  in TFOCS so I can compute the sum of the L2 norms for intervals in each row.

e.g. 

input matrix: 
```
x = 1  1  2  2
    3  3  4  4
```

original L1-L2 norm in TFOCS will give `sqrt(1^2 + 1^2 + 2^2 + 2^2) + sqrt(3^2 + 3^2 + 4^2 + 4^2)`

now I have a variable `group_len` that determines lengths of groups separated in rows and sum likewise

say `group_len = 2`, then the desired norm value is `sqrt(1^1 + 1^1) + sqrt(2^2 + 2^2) + sqrt(3^2 + 3^2) + sqrt(4^2 + 4^2)`

In `prox_l1_l2.m`, I think the first function `v = f(q,x)` calculates the norm, and I added as follows. I believe this one should be correct. However I'm confused about how to modify `prox_f_bsxfun` (I'm using MATLAB 2018a), I know it's to compute the proximity operator of the norm, but not sure if I'm modifying it correctly or how to validate its correctness. Any suggestions?

```
function v = f(q, group_len, x)
    [row_num, col_num] = size(x);
    y = reshape(x', group_len, row_num * col_num / group_len)';
    v = sum( q.* sqrt(sum(y.^2, 2)) );
end
```

```
function x = prox_f_bsxfun(q, group_len, x,t)
  [row_num, col_num] = size(x);
  y = reshape(x', group_len, row_num * col_num / group_len)';
  v1 = sqrt( sum(y.^2, 2) );
  v2 = reshape(v1', col_num / group_len, row_num);
  v = sum(v2, 1)';
  s = 1 - 1 ./ max( v ./ ( t .* q ), 1 );
  x = bsxfun( @times, x, s ); % Apr 24 2013. Should be faster
end
```

**Comment by stephenbeckr** [comment]
Sorry for the slow response.  I think you have the right idea with the reshape. Basically, we have the forward reshape operator `A = @(x) reshape( x', group_len, [] )`,  and then its inverse/adjoint `At = @(y) reshape( y', 4, [] )'` (where `4` is the number of columns in the original variable, so adjust accordingly -- check for bugs there!). 

In `prox_f_bsxfun` part, it's probably simplest to overwrite `x` as `x = A(x)` where `A` is defined as above, then let the entire function run, and at the very last line, update again with `x = At(x)`. I think your `v2` above, which undos some reshaping, might be too early in the code. Let the `bsxfun` line execute, then use the `At` reshape to undo.

The code you have could be correct, but if you're worried, try it as I suggest above. And I always run unit tests using CVX to check my answer. If you can code this prox up into CVX, you can verify it's doing the right thing for various random inputs.

**Comment by snapfinger** [comment]
I see, thanks!
