### ISSUE TITLE
Error syntax

### ISSUE THREAD

**Issue by ChenZhongPu** [cvxr/TFOCS#2]
When I try to run :

>Error: A BREAK may only be used within a FOR or WHILE loop, and then only
within the same file as its corresponding FOR or WHILE statement.
>Error in tfocs_AT (line 78)
        tfocs_backtrack

**Comment by stephenbeckr** [comment]
Can you tell me when/where you downloaded TFOCS? The latest version on
github has fixed this bug.
Best, Stephen
