### ISSUE TITLE
solver_sNuclearBP problem

### ISSUE THREAD

**Issue by wkelongws** [cvxr/TFOCS#4]
solver_sNuclearBP uses N=16 in the "matrix completion" demo. But whenever you run it once, then you can not change N to another value. For example, you first run with N=16, then try to run with N=18 and it will return error message "bad height dimension for warmStart". The same thing will happen if you run with N=18 first then run with N=16. Anytime you want to run the solver on a matrix with different N, you need restart MATLAB.

**Comment by alitk** [comment]
Same problem here. Have you found any solution for that?

**Comment by stephenbeckr** [comment]
There was a bug with a persistent variable not being reset properly. It's fixed now. Sorry @wkelongws for forgetting about this!
