### ISSUE TITLE
Avoid too wild values with tfocs

### ISSUE THREAD

**Issue by cwliu007** [cvxr/TFOCS#6]
Hi,
I am very new to tfocs. Firstly, I play a normal optimization like
`[newx,out,OPTS] = tfocs( funObj, [], [], x ,OPTS);`
But it always failed in first run and return `nan`. I found that the iterative values of `x` went too wildly so that my `funObj` cannot compute a value. How can I set up the optimizer of tfocs to give small increment of `x` (e.g., <=0.5) in every iteration for 'stabilizing` the optimization. Thanks!

**Comment by stephenbeckr** [comment]
Hi,
  TFOCS will auto-tune the increments, so I think the issue here may be with your function. Can you give us a simple version of your code that still gives the error?  For guaranteed convergence, we need the function to have a Lipschitz continuous gradient, and while sometimes you can get away without this assumption in practice (depending on how the function behaves near the solution and near your initial point), it is sometimes necessary.

**Comment by genwei007** [comment]
Thanks for reply! Please download files from https://drive.google.com/file/d/0B4lSE7Qt4c3JM1A3RnVHeEt5dGM/view?usp=sharing and run `example_UM.m`. The major function to be called to calculate likelihood function is `UMfun.m`. It cannot calculate with too large values of parameters. Besides, I have tested on many optimizers (see `runSingleEM.m`) and they all succeed on my example. Hope you may have a look and test. Thank you!

**Comment by stephenbeckr** [comment]
Hi,
  That's a bit complicated for me to debug. I just committed the file `test_Lipschitz.m` to the repo. Can you use that file and test your gradient function with it (and try the scale parameter)? You can put in what you think is the Lipschitz constant of the gradient, and this code will see if it can find any violations. If you don't know the Lipschitz constant, then just re-run this code a lot and see if the Lipschitz constant estimate it provides is bounded or if sometimes it is really large.

**Comment by genwei007** [comment]
I don't know the Lipschitz constant, so I tried scale = .01 and got the following results (partially):
~~~
   3.5371e+03

   1.8033e+03

   1.5366e+03

   1.9250e+03

   2.6083e+03

   2.1575e+08

   1.3379e+05

   5.7487e+03

   1.2495e+08

   1.5308e+03

   2.3710e+03

  979.8913

   1.1889e+03

   5.2255e+08

   3.5104e+08

   2.1175e+08

   1.9111e+03

   2.7328e+08

   1.8209e+05

   1.9110e+09

   1.6545e+03

   1.4893e+03

   2.0186e+08

   1.6035e+03

   1.0778e+10
...
~~~

**Comment by stephenbeckr** [comment]
That seems suspicious to me, as most estimates are around 1000, but then it sometimes jumps to 10 billion.  In this region, the stepsize would have to be about 1e-10, and that's likely a problem. It could be that your function just does not have a Lipschitz continuous gradient, or that perhaps the gradient calculation has a bug.  If you can simplify it to a few dozen lines of code, there's a better chance I could help with the debugging.
