### ISSUE TITLE
stopfcn problem in tfocs_iterate.m

### ISSUE THREAD

**Issue by bradicator** [cvxr/TFOCS#9]
TFOCS v1.4
MATLAB version 9.0 (R2016a) on MACI64

Hi, in v1.4 and the current version on github, in file tfocs_iterate.m, line 85, 
`if isa(stopFcn,'function_handle') % added Oct 27 '14` is wrong. The reason is because by the design in tfocs_initialize.m, stopFcn is a cell containing function_handle rather than function_handle itself. The fix is 
`if isa(stopFcn{err_j},'function_handle')`. One does not need to run the program to verify this; reading the context of this line is convincing enough. The consequence of this bug is that user defined stop functions never run...

Best,
Brad

**Comment by stephenbeckr** [comment]
You're right, good catch. Thanks! Just pushed the fix to github
